site_name: Monad CMS
site_url: http://monad.monomelodies.nl/docs/
repo_url: https://github.com/monomelodies/monad

pages:
- Overview:
    - 'Home': 'index.md'
    - 'A little history': 'overview/history.md'
    - 'Main concepts': 'overview/main.md'
    - 'Basic customisation': 'overview/customisation.md'
    - 'Authentication': 'overview/authentication.md'
    - 'Models': 'overview/models.md'
    - 'Navigation': 'overview/navigation.md'
- Components:
    - 'Setup': 'components/setup.md'
    - 'Managers': 'components/managers.md'
    - 'Models': 'components/models.md'
    - 'Controllers': 'components/controllers.md'
    - 'Templates': 'components/templates.md'
    - 'Custom directives, filters and other stuff': 'components/custom.md'
- Directives:
    - 'moPath': 'directives/path.md'
    - 'moSlug': 'directives/slug.md'
    - 'moList': 'directives/list.md'
    - 'moListHeader': 'directives/list/header.md'
    - 'moListTable': 'directives/list/table.md'
    - 'moUpdate': 'directives/update.md'
    - 'moField': 'directives/field.md'
    - 'moDragDrop': 'directives/dragdrop.md'
- Examples:
    - 'Adding a custom homepage or dashboard': 'samples/home.md'
    - 'Translating your administrator': 'samples/translate.md'
    - 'CRUD with multiple models': 'samples/multi.md'
    - 'Filtering lists': 'samples/filtering.md'
    - 'Messages': 'samples/messaging.md'
    - 'Integrating CKEditor': 'samples/ckeditor.md'
    - 'File uploads': 'samples/files.md'
    - 'Sub-authentication': 'samples/subauthentication.md'
    - 'Building reusable components': 'samples/reusable.md'
    - 'Wordpress plugin': 'samples/wordpress.md'

copyright: Copyright &copy; 2015, 2016, <a href="http://www.monomelodies.nl/">Marijn Ophorst</a>

