site_name: Monad CMS
site_url: http://monad.monomelodies.nl/docs/
repo_url: https://github.com/monomelodies/monad

pages:
- Overview:
    - 'Home': 'index.md'
    - 'A little history': 'overview/history.md'
    - 'Prerequisites': 'overview/prerequisites.md'
- Building blocks:
    - 'Components': 'blocks/components.md'
    - 'Template components and directives': 'blocks/template.md'
    - 'Models': 'blocks/models.md'
    - 'Translating your administrator': 'blocks/translate.md'
    - 'Filtering lists': 'blocks/filtering.md'
    - 'Messages': 'blocks/messaging.md'
- Advanced techniques:
    - 'Adding a custom homepage or dashboard': 'advanced/home.md'
    - 'Authentication example': 'advanced/authentication.md'
    - 'CRUD with multiple models': 'advanced/multi.md'
    - 'Integrating CKEditor': 'advanced/ckeditor.md'
    - 'File uploads': 'advanced/files.md'
    - 'Sub-authentication': 'advanced/subauthentication.md'
    - 'Building reusable components': 'advanced/reusable.md'
- Examples:
    - 'Multi-level authentication': 'examples/authentication.md'

copyright: Copyright &copy; 2015, 2016, 2017 <a href="http://www.monomelodies.nl/">Marijn Ophorst</a>

