site_name: Monad CMS
site_url: http://monad-cms.readthedocs.org/en/latest/
repo_url: https://github.com/monomelodies/monad
theme: united

pages:
- [index.md, Overview, Home]
- [overview/history.md, Overview, A little history]
- [overview/build.md, Overview, Setting up a build script]
- [overview/main.md, Overview, Main concepts]
- [overview/customisation.md, Overview, Basic customisation]
- [overview/authentication.md, Overview, Authentication]

- [components/setup.md, Components, Setup]
- [components/managers.md, Components, Managers]
- [components/models.md, Components, Models]
- [components/controllers.md, Components, Controllers]
- [components/templates.md, Components, Templates]
- [components/custom.md, Components, "Custom directives, filters and other stuff"]

- [classes/monad.md, Classes, Monad global object]
- [classes/component.md, Classes, Component]
- [classes/model.md, Classes, Model]
- [classes/collection.md, Classes, Collection]

- [services/authentication.md, Services, Authentication]
- [services/language.md, Services, Language]
- [services/manager.md, Services, Manager]

- [controllers/crud.md, Controllers, CrudController]

- [directives/path.md, Directives, moPath]
- [directives/slug.md, Directives, moSlug]
- [directives/list.md, Directives, moList]
- [directives/list/header.md, Directives, moListHeader]
- [directives/list/table.md, Directives, moListTable]
- [directives/update.md, Directives, moUpdate]

- [samples/home.md, Examples, Adding a custom homepage or dashboard]
- [samples/multi.md, Examples, CRUD with multiple models]
- [samples/ckeditor.md, Examples, Integrating CKEditor]
- [samples/files.md, Examples, File uploads]
- [samples/subauthentication.md, Examples, Sub-authentication]
- [samples/reusable.md, Examples, Building reusable components]
- [samples/wordpress.md, Examples, Wordpress plugin]

copyright: Copyright &copy; 2015, <a href="http://www.monomelodies.nl/">Marijn Ophorst</a>

