site_name: Monad CMS
site_url: http://monad-cms.readthedocs.org/en/latest/
repo_url: https://github.com/monomelodies/monad
theme: united

pages:
- [index.md, Overview, Home]
- [overview/history.md, Overview, A little history]
- [overview/build.md, Overview, Setting up a build script]
- [overview/minimal.md, Overview, Basic concepts]
- [overview/customisation.md, Overview, Basic customisation]
- [overview/authentication.md, Overview, Authentication]

- [components/setup.md, Components, Setup]
- [components/managers.md, Components, Managers]
- [components/models.md, Components, Models]
- [components/controllers.md, Components, Controllers]
- [components/templates.md, Components, Templates]
- [components/custom.md, Components, "Custom directives, filters and other stuff"]

- [classes/model.md, Classes, Model]
- [classes/collection.md, Classes, Collection]

- [services/authentication.md, Services, Authentication]
- [services/language.md, Services, Language]
- [services/manager.md, Services, Manager]

- [directives/path.md, Directives, Path]
- [directives/lists.md, Directives, Lists]
- [directives/forms.md, Directives, Forms]

- [samples/home.md, Examples, Adding a custom homepage or dashboard]
- [samples/ckeditor.md, Examples, Integrating CKEditor]
- [samples/files.md, Examples, File uploads]
- [samples/subauthentication.md, Examples, Sub-authentication]
- [samples/wordpress.md, Examples, Wordpress plugin]

copyright: Copyright &copy; 2015, <a href="http://www.monomelodies.nl/">Marijn Ophorst</a>

