site_name: Monad CMS

pages:
- [index.md, Overview, Home]
- [overview/build.md, Overview, Setting up a build script]
- [overview/minimal.md, Overview, Basic concepts]
- [overview/authentication.md, Overview, Authentication]

- [components/index.md, Components, Introduction]
- [components/basic.md, Components, Create a basic component]
- [components/advanced.md, Components, Advanced component options]
- [components/linking.md, Components, Linking components together]

- [directives/lists.md, Directives, Lists]
- [directives/forms.md, Directives, Forms]

- [recipes/files.md, Common recipes, File uploads]

- [samples/index.md, Samples, Wordpress plugin]

theme: readthedocs
