site_name: Monad CMS
site_url: http://monad.monomelodies.nl/docs/
repo_url: https://github.com/monomelodies/monad

pages:
- Overview:
    - 'Home': 'index.md'
    - 'A little history': 'overview/history.md'
    - 'Setting up a build script': 'overview/build.md'
    - 'Main concepts': 'overview/main.md'
    - 'Basic customisation': 'overview/customisation.md'
    - 'Authentication': 'overview/authentication.md'
- Components:
    - 'Setup': 'components/setup.md'
    - 'Managers': 'components/managers.md'
    - 'Models': 'components/models.md'
    - 'Controllers': 'components/controllers.md'
    - 'Templates': 'components/templates.md'
    - 'Custom directives, filters and other stuff': 'components/custom.md'
- Classes:
    - 'Monad global object': 'classes/monad.md'
    - 'Component': 'classes/component.md'
    - 'Model': 'classes/model.md'
    - 'Collection': 'classes/collection.md'
- Services:
    - 'Authentication': 'services/authentication.md'
    - 'Navigation': 'services/navigation.md'
    - 'Language': 'services/language.md'
    - 'Manager': 'services/manager.md'
- Controllers:
    - 'RootController': 'controllers/root.md'
    - 'LoginController': 'controllers/login.md'
    - 'HomeController': 'controllers/home.md'
    - 'ListController': 'controllers/list.md'
    - 'CrudController': 'controllers/crud.md'
- Directives:
    - 'moPath': 'directives/path.md'
    - 'moSlug': 'directives/slug.md'
    - 'moList': 'directives/list.md'
    - 'moListHeader': 'directives/list/header.md'
    - 'moListTable': 'directives/list/table.md'
    - 'moUpdate': 'directives/update.md'
    - 'moDragDrop': 'directives/dragdrop.md'
- Examples:
    - 'Adding a custom homepage or dashboard': 'samples/home.md'
    - 'CRUD with multiple models': 'samples/multi.md'
    - 'Integrating CKEditor': 'samples/ckeditor.md'
    - 'File uploads': 'samples/files.md'
    - 'Sub-authentication': 'samples/subauthentication.md'
    - 'Building reusable components': 'samples/reusable.md'
    - 'Wordpress plugin': 'samples/wordpress.md'

copyright: Copyright &copy; 2015, <a href="http://www.monomelodies.nl/">Marijn Ophorst</a>

